---
#Provide your username below and uncomment it
#username: 
user:
  name: "{{ username }}"
  groups: 
    - "{{ username }}"
    - wheel
  home: "/home/{{ username }}"
curr_home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
