- name: Get latest release of a public repository
  community.general.github_release:
    user: ahrm
    repo: sioyek
    action: latest_release
  register: release

- name: Make sure directory .local/bin is present
  ansible.builtin.file:
    path: "{{ user.home }}/.local/bin"
    state: directory
    mode: '751'
- name: Unzip to the .local/bin
  ansible.builtin.unarchive:
    remote_src: true
    src: "https://github.com/ahrm/sioyek/releases/download/{{release['tag']}}/sioyek-release-linux.zip"
    dest: "{{ user.home }}/Downloads/"
    creates: "{{ user.home }}/Downloads/sioyek-release-linux.zip"
    list_files: true
  register: archive
- name: Rename archived file to sioyek
  ansible.builtin.copy:
    src: "{{ user.home }}/Downloads/{{ archive['files'][0] }}"
    dest: "{{ user.home }}/.local/bin/sioyek"
    mode: '751'
