---
- name: Configure Arch Linux
  hosts: localhost
  tasks:
  - name: Clone dmenu
    ansible.builtin.git:
      repo: https://github.com/tvha23/dmenu.git
      dest: /home/tvha/.config/dmenu/
      clone: true
      update: true
  - name: Install dmenu
    become: yes
    ansible.builtin.shell:
      chdir: /home/tvha/.config/dmenu/
      cmd: rm config.h; make clean install
