---
- name: Configure Arch Linux
  hosts: localhost
  tasks:
  - name: Clone dwm
    ansible.builtin.git:
      repo: https://github.com/tvha23/dwm.git
      dest: /home/tvha/.config/dwm/
      clone: true
      update: true
  - name: Install dwm
    become: yes
    ansible.builtin.shell:
      chdir: /home/tvha/.config/dwm/
      cmd: rm config.h; make clean install
