---
- name: Configure Arch Linux
  hosts: localhost
  tasks:
  - name: Install xorg packages
    become: true
    community.general.pacman:
      name:
        #Audio
        - pipewire
        - pipewire-alsa
        - pipewire-pulse
        - wireplumber

          #Xorg
        - xorg-server
        - xorg-setxkbmap
        - xorg-xauth
        - xorg-xev
        - xorg-xinit
        - xorg-xinput
        - xorg-xrandr
        - xorg-xrdb
        - xorg-xset
        - xclip

          #Zsh
        - zsh
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - pkgfile

          #Fonts
        - ttf-iosevkaterm-nerd
        - ttf-iosevka-nerd

          #Dwmblocks-async dependencies
        - libxcb
        - xcb-proto
        - xcb-util
        - pkg-config

          #Terminal
        - kitty

          #Multimedia
        - mpd
        - mpc
        - mpv
        - ncmpcpp
        - vlc
        - nsxiv

          #Misc.
        - sxhkd
        - numlockx
        - maim
      state: present

