---
- name: Configure Arch Linux
  hosts: localhost
  tasks:
  - name: Clone configuration files from github
    ansible.builtin.git:
      repo: https://github.com/tvha23/config-files.git
      dest: /home/tvha/Downloads/config-files/
      clone: true
      update: true

  - name: Enable pipewire pulseaudio service
    ansible.builtin.systemd_service:
      name: pipewire-pulse.service
      scope: user
      enabled: true
      state: started
