---
- name: Configure Arch Linux
  hosts: localhost
  tasks:
  - name: Clone configuration files from github
    ansible.builtin.git:
      repo: https://github.com/tvha23/config-files.git
      dest: /home/tvha/Downloads/config-files/
      clone: true
      update: true

  - name: Place zsh configuration file
    ansible.builtin.copy:
      src: /home/tvha/Downloads/config-files/.zshrc
      dest: /home/tvha/.zshrc

  - name: Change shell to zsh
    become: true
    ansible.builtin.shell:
      cmd: usermod -s /usr/bin/zsh tvha

  - name: Install xorg packages
    become: true
    community.general.pacman:
      name:
        - pipewire
        - pipewire-alsa
        - pipewire-pulse
        - wireplumber
        - xorg-server
        - xorg-setxkbmap
        - xorg-xauth
        - xorg-xev
        - xorg-xinit
        - xorg-xinput
        - xorg-xrandr
        - xorg-xrdb
        - xorg-xset
        - zsh
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - pkgfile
        - ttf-iosevkaterm-nerd
        - ttf-iosevka-nerd
        - libxcb #dwmblocks
        - xcb-proto #deps
        - xcb-util
        - pkg-config
        - kitty
      state: present

  - name: Enable pipewire pulseaudio service
    ansible.builtin.systemd_service:
      name: pipewire-pulse.service
      scope: user
      enabled: true
      state: started

  - name: Place touchpad configuration file
    become: yes
    ansible.builtin.copy:
      src: /home/tvha/Downloads/config-files/40-libinput.conf
      dest: /etc/X11/xorg.conf.d/40-libinput.conf

  - name: Place keyboard configuration file
    become: yes
    ansible.builtin.copy:
      src: /home/tvha/Downloads/config-files/00-keyboard.conf
      dest: /etc/X11/xorg.conf.d/00-keyboard.con

  - name: Place .xinitrc file
    ansible.builtin.copy:
      src: /home/tvha/Downloads/config-files/.xinitrc
      dest: /home/tvha/.xinitrc

  - name: Clone dwm
    ansible.builtin.git:
      repo: https://github.com/tvha23/dwm.git
      dest: /home/tvha/.config/dwm/
      clone: true
      update: true
  - name: Install dwm
    become: yes
    ansible.builtin.shell:
      chdir: /home/tvha/.config/dwm/
      cmd: rm config.h; make clean install

  - name: Clone dmenu
    ansible.builtin.git:
      repo: https://github.com/tvha23/dmenu.git
      dest: /home/tvha/.config/dmenu/
      clone: true
      update: true
  - name: Install dmenu
    become: yes
    ansible.builtin.shell:
      chdir: /home/tvha/.config/dmenu/
      cmd: rm config.h; make clean install

  - name: Clone dwmblocks-async
    ansible.builtin.git:
      repo: https://github.com/tvha23/dwmblocks-async.git
      dest: /home/tvha/.config/dwmblocks-async/
      clone: true
      update: true
  - name: Install dwmblocks-async
    become: yes
    ansible.builtin.shell:
      chdir: /home/tvha/.config/dwmblocks-async/
      cmd: make clean install

  - name: Make sure kitty dir is present in .config dir
    ansible.builtin.file:
      path: /home/tvha/.config/kitty
      state: directory
 
  - name: Place kitty config
    ansible.builtin.copy:
      src: /home/tvha/Downloads/config-files/kitty.conf
      dest: /home/tvha/.config/kitty/kitty.conf


