---
- name: Upgrade the system
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  become: true
  community.general.pacman:
    name:
      - acpi
      - alsa-utils
      - ansible
      - arandr
      - base
      - base-devel
      - bat
      - bc
      - brightnessctl
      - colordiff
      - firefox
      - fzf
      - git
      - gvfs
      - gvfs-mtp
      - gvfs-nfs
      - htop
      - inetutils
      - intel-ucode
      - iw
      - iwd
      - kitty
      - libreoffice-fresh
      - libxcb
      - linux-firmware
      - maim
      - mpc
      - mpd
      - mpv
      - ncmpcpp
      - neovim
      - nicotine+
      - nnn
      - npm
      - nsxiv
      - ntfs-3g
      - numlockx
      - obsidian
      - openssh
      - p7zip
      - pavucontrol
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pkgconfig
      - pkgfile
      - python
      - qbittorrent
      - qemu-base
      - reflector
      - ripgrep
      - rsync
      - rust
      - speech-dispatcher
      - sxhkd
      - syncthing
      - telegram-desktop 
      - thunar
      - thunar-volman
      - ttf-font-awesome
      - ttf-iosevka-nerd
      - ttf-iosevkaterm-nerd
      - udiskie
      - unrar
      - unzip
      - vi
      - vim
      - vlc
      - wget
      - wireplumber
      - xcb-proto
      - xcb-util
      - xclip
      - xorg-server
      - xorg-setxkbmap
      - xorg-xauth
      - xorg-xbacklight
      - xorg-xev
      - xorg-xinit
      - xorg-xinput
      - xorg-xrandr
      - xorg-xrdb
      - xorg-xset
      - yt-dlp
      - zathura
      - zathura-djvu
      - zathura-pdf-mupdf 
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting

- name: Install packages from AUR
  become: true
  community.general.pacman:
    executable: paru
    name:
      - dynamips 
      - gns3-gui 
      - gns3-server 
      - nbfc-linux 
      - paru-bin 
      - sioyek-appimage 
      - ubridge 
      - ungoogled-chromium-bin 
      - vpcs 
