---
- name: Place .xinitrc file
  ansible.builtin.copy:
    src: files/.xinitrc
    dest: "{{ curr_home }}/.xinitrc"

- name: Place .Xresources configuration file
  ansible.builtin.copy:
    src: files/.Xresources
    dest: "{{ curr_home }}/.Xresources"

- name: Place touchpad configuration file
  become: yes
  ansible.builtin.copy:
    src: files/40-libinput.conf
    dest: /etc/X11/xorg.conf.d/40-libinput.conf

- name: Place keyboard configuration file
  become: yes
  ansible.builtin.copy:
    src: files/00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
