---
- name: Clone dwm
  ansible.builtin.git:
    repo: git@github.com:swivelmargarita/dwm.git
    dest: "{{ curr_home }}/.config/dwm/"
    clone: true
    update: true
- name: Install dwm
  become: yes
  ansible.builtin.shell:
    chdir: "{{ curr_home }}/.config/dwm/"
    cmd: rm config.h; make clean install
