---
- name: Place zsh configuration file
  ansible.builtin.copy:
    src: files/.zshrc
    dest: "{{ curr_home}}/.zshrc"


- name: Change shell to zsh
  become: true
  ansible.builtin.shell:
    cmd: "usermod -s /usr/bin/zsh {{ lookup('ansible.builtin.env', 'USER') }}"
