---
- name: Make sure sxhkd dir is present in .config dir
  ansible.builtin.file:
    path: "{{ curr_home }}/.config/sxhkd"
    state: directory

- name: Place sxhkd config
  ansible.builtin.copy:
    src: files/sxhkdrc
    dest: "{{ curr_home }}/.config/sxhkd/sxhkdrc"

      #- name: Make sure systemd/user dir is present in .config dir
      #  ansible.builtin.file:
      #    path: "{{ curr_home }}/.config/systemd/user"
      #    state: directory
      #
      #- name: Put sxhd.service in .config/systemd/user
      #  ansible.builtin.copy:
      #    src: files/sxhkd.service
      #    dest: "{{ curr_home }}/.config/systemd/user/sxhkd.service"
      #
      #- name: Enable sxhkd service
      #  ansible.builtin.systemd_service:
      #    name: sxhkd.service
      #    scope: user
      #    enabled: true
      #    state: started
