---
- name: Make sure kitty dir is present in .config dir
  ansible.builtin.file:
    path: "{{ curr_home }}/.config/kitty"
    state: directory

- name: Place kitty config
  ansible.builtin.copy:
    src: files/kitty.conf
    dest: "{{ curr_home }}/.config/kitty/kitty.conf"
