---
- name: Put init.lua into config folder
  ansible.builtin
---
- name: Make sure kitty dir is present in .config dir
  ansible.builtin.file:
    path: "{{ curr_home }}/.config/nvim"
    state: directory

- name: Place kitty config
  ansible.builtin.copy:
    src: files/init.lua
    dest: "{{ curr_home }}/.config/nvim/"
